### PR TITLE
Update integration sample magento

### LINKED ISSUE #148: Update integration sample - Magento
### Brief bug description

After the [rebranding from Kentico Cloud to Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent) there are still some samples that use old naming in branches named `samples/*`.

Until the end of October endpoint on domain `kenticocloud.com` stop working and there will be redirect performed:
* https://docs.kontent.ai/reference/api-changelog#a-api-urls-changed

#### Transfer changes made in https://github.com/Kentico/kontent-sample-app-react/pull/140 to the [**`samples/magento`**](https://github.com/Kentico/kontent-sample-app-react/tree/samples/magento) branch

* Update dependency from `kentico-cloud-delivery` to `@kentico/kontent-delivery`
    * adjust the breaking changes
* Update dependency `@chevtek/react-spinners` to `@simply007org/react-spinners`
   * no breaking changes
* Rename Kentico Cloud to Kentico Kontent
* adjust `travis.yml` to use the correct domain for deployment

### PR DESCRIPTION
**Pull request by mgroovyank**
### Motivation

Fixes #148 

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by mgroovyank** [comment]
@Simply007 I think I'm missing some changes in the **package-lock.json** file. Am I right?

**Comment by Simply007** [comment]
yeap - I would recommend cloning your [branch with the fixes](https://github.com/mgroovyank/kontent-sample-app-react/tree/Update-integration-sample-Magento) and run npm install to generate package-lock.json and commit it to the pull request.

**Comment by mgroovyank** [comment]
@Simply007 do I need to do all the changes same as in  https://github.com/Kentico/kontent-sample-app-react/pull/140/files 
?

**Comment by mgroovyank** [comment]
Hi @Simply007, 
Makinge the changes same as in  https://github.com/Kentico/kontent-sample-app-react/pull/140/files
in the Home page file gives an error like this - 
Attempted import error: 'getAboutUsLink' is not exported from '../Utilities/ContentLinks'.

**Comment by Simply007** [comment]
I have set up the automatic preview for the pull requests:
to see whether the site is working see: https://deploy-preview-151--kontent-sample-app-react.netlify.com/

Most of the pages are working, just About Us section, detail of the product and article detail needs to  adjustments according to the breaking changes in JS SDK:
* https://github.com/Kentico/kentico-kontent-js/blob/master/packages/delivery/UPGRADE.md#upgrading-from-5xy-to-600

**Comment by mgroovyank** [comment]
@Simply007 Sorry for the delay. All the pages are working now.

**Pull request merged**
